const productos = [
    {
        id: "bici de mtb",
        titulo: "Bici de mtb",
        imagen: "./imagenes/bmc-fourstroke-mtb-01.jpg",
        precio: 1445000,
        cantidad: 1,
    },
    {
        id: "bici de mtb",
        titulo: "Bici de mtb",
        imagen: "./imagenes/bicis-scott-mtb-02.jpg",
        precio: 185000,
        cantidad: 1,
    },
    {
        id: "bici de mtb",
        titulo: "Bici de mtb",
        imagen: "./imagenes/bici-canyon.jpg",
        precio: 134000,
        cantidad: 1,
    },
    {
        id: "bici de mtb",
        titulo: "Bici de mtb",
        imagen: "./imagenes/trek-mtb-04.jpg",
        precio: 7570000,
        cantidad: 1,
    },
    {
        id: "bici de mtb",
        titulo: "Bici de mtb",
        imagen: "./imagenes/specialized-epic-mtb-05.jpg",
        precio: 1742000,
        cantidad: 1,
    },
    {
        id: "bici de enduro",
        titulo: "Bici de enduro",
        imagen: "./imagenes/bici-enduro-01.jpg",
        precio: 7250000,
        cantidad: 1,
    },
    {
        id: "bici de enduro",
        titulo: "Bici de enduro",
        imagen: "./imagenes/bici-enduro-02.jpg",
        precio: 4560000,
        cantidad: 1,
    },
    {
        id: "bici de enduro",
        titulo: "Bici de enduro",
        imagen: "./imagenes/bici-enduro-03.jpeg",
        precio: 5670000,
        cantidad: 1,
    },

    {
        id: "bici de enduro",
        titulo: "Bici de enduro",
        imagen: "./imagenes/bici-enduro-04.jpg",
        precio: 5672000,
        cantidad: 1,
    },
    {
        id: "bici de enduro",
        titulo: "Bici de enduro",
        imagen: "./imagenes/bici-enduro-05.jpg",
        precio: 6790000,
        cantidad: 1,
    },
    {
        id: "bici de descenso",
        titulo: "Bici de descenso",
        imagen: "./imagenes/bici-descenso-01.jpg",
        precio: 4567000,
        cantidad: 1,
    },
    {
        id: "bici de descenso",
        titulo: "Bici de descenso",
        imagen: "./imagenes/bici-descenso-02.jpg",
        precio: 4567800,
        cantidad: 1,
    },
    {
        id: "bici de descenso",
        titulo: "Bici de descenso",
        imagen: "./imagenes/bici-descenso-03.jpg",
        precio: 6200,
        cantidad: 1,
    },
    {
        id: "bici de descenso",
        titulo: "Bici de descenso",
        imagen: "./imagenes/bici-enduro-04.jpg",
        precio: 3589000,
        cantidad: 1,
    },
    {
        id: "bici de descenso",
        titulo: "Bici de descenso",
        imagen: "./imagenes/bici-descenso-05.jpg",
        precio: 9875000,
        cantidad: 1,
    },
    {
        id: "frenos xt",
        titulo: "Frenos xt",
        imagen: "./imagenes/freno-xt-01.jpg",
        precio: 140000,
        cantidad: 1,
    },

    {
        id: "frenos xt",
        titulo: "Frenos xt",
        imagen: "./imagenes/frenos-xt-02jpg.jpg",
        precio: 157000,
        cantidad: 1,
    },
    {
        id: "frenos slx",
        titulo: "Frenos slx",
        imagen: "./imagenes/frenos-slx-03.jpg",
        precio: 130000,
        cantidad: 1,
    },
    {
        id: "frenos slx",
        titulo: "Frenos slx",
        imagen: "./imagenes/frenos-slx-04.webp",
        precio: 128000,
        cantidad: 1,
    },
    {
        id: "pinza de freno",
        titulo: "pinza de freno",
        imagen: "./imagenes/pinzadefreno.01.jpeg",
        precio: 90000,
        cantidad: 1,
    },
    {
        id: "transmision slx",
        titulo: "transmision slx",
        imagen: "./imagenes/transmision-slx.jpeg",
        precio: 180000,
        cantidad: 1,
    },
    {
        id: "transmision slx",
        titulo: "transmision slx",
        imagen: "./imagenes/transmision-xt01.jpeg",
        precio: 210000,
        cantidad: 1,
    },
    {
        id: "disco de freno",
        titulo: "disco de freno",
        imagen: "./imagenes/disco-de-freno-descenso-01.jpg",
        precio: 60000,
        cantidad: 1,
    },
    {
        id: "pedales mtb",
        titulo: "pedales mtb",
        imagen: "./imagenes/pedales-mtb-01.jpeg",
        precio: 65000,
        cantidad: 1,
    },
    {
        id: "pedales mtb",
        titulo: "pedales mtb",
        imagen: "./imagenes/pedales-mtb-01.jpeg",
        precio: 24000,
        cantidad: 1,
    },
    {
        id: "pedales mtb",
        titulo: "pedales mtb",
        imagen: "./imagenes/pedales-mtb-02.jpg",
        precio: 25000,
        cantidad: 1,
    },
    {
        id: "pedales mtb",
        titulo: "pedales mtb",
        imagen: "./imagenes/pedales-mtb-02.jpg",
        precio: 67000,
        cantidad: 1,
    },
    {
        id: "pedales mtb",
        titulo: "pedales mtb",
        imagen: "./imagenes/pedales-mtb-03.webp",
        precio: 70000,
        cantidad: 1,
    },

];